CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    is_banned BOOLEAN DEFAULT FALSE,
    role VARCHAR(50) DEFAULT 'user' CHECK (role IN ('admin', 'user')) NOT NULL,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pixels(
    id SERIAL PRIMARY KEY,
    x INT NOT NULL,
    y INT NOT NULL,
    color CHAR(7) NOT NULL,
    placed_by INT NOT NULL REFERENCES users(id),
    placed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
